version: '3'
services:
  web: 
    build: backend
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    environment: 
      FLASK_APP: app
      FLASK_DEBUG: true
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      CLOUDINARY_URL: cloudinary://319854841752268:HQa86nLhkmp2RIL9sLEaHp8GCEE@dfms5eutq
      SECRET_KEY: My_secret_key
    volumes:
      - ./backend:/app
    depends_on:
      - db
  react:
   build: frontend
   ports:
     - '3000:3000'
   volumes:
     - ./frontend:/app/frontend
   depends_on:
     - web
  db:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local  
  