version: '3'
services:
  backend: 
    build: backend #u koji folder da udje i nadje Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    environment: 
      FLASK_APP: main
      FLASK_DEBUG: true
      FLASK_ENV: development #lazy load u development modu zato je dobar
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres  #://user:password@db je ime 16 linija:5432/DB_name
    volumes:
      - ./backend:/backend          #moj kod gdje se nalazi mapiram na workdir fodler flask
    depends_on:
      - db
  #frontend:
   # build: frontend
   # ports:
   #   - '4002:3000'
   # volumes:
  #    - ./frontend:/usr/src/app
   # depends_on:
   #   - db
   #   - backend
  db:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local  
  