version: '3'
services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app          #moj kod gdje se nalazi mapiram na workdir fodler flask
    depends_on:
      - db
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306