"""Accouncment owner key

Revision ID: 878390024bcb
Revises: a0f6ff70254e
Create Date: 2022-12-29 18:40:30.056495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878390024bcb'
down_revision = 'a0f6ff70254e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
