"""Announcment

Revision ID: ac9f421133bf
Revises: 
Create Date: 2022-12-25 12:22:24.394983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9f421133bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=700), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('announcement')
    # ### end Alembic commands ###
